/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1c1b',
        'tertiary-fixed': '#e2e2e2',
        'surface-bright': '#faf9f7',
        'secondary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed-variant': '#454747',
        'on-secondary-fixed-variant': '#474747',
        'on-error': '#ffffff',
        'outline-variant': '#d8c1c0',
        background: '#faf9f7',
        'secondary-fixed': '#e4e2e1',
        'surface-container-low': '#f4f3f1',
        'on-surface-variant': '#534342',
        outline: '#867372',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#ffb3b1',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e3e2e0',
        'on-background': '#1a1c1b',
        'surface-tint': '#904a49',
        'on-secondary-container': '#656464',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-variant': '#e3e2e0',
        'inverse-primary': '#ffb3b1',
        'primary-fixed': '#ffdad8',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e9e8e6',
        'on-tertiary-container': '#b2b3b3',
        error: '#ba1a1a',
        'secondary-container': '#e4e2e1',
        'inverse-on-surface': '#f1f1ef',
        'on-tertiary': '#ffffff',
        secondary: '#5f5e5e',
        'surface-container': '#efeeec',
        'primary-container': '#713131',
        tertiary: '#2d2f2f',
        'on-primary-container': '#f39b99',
        primary: '#551b1c',
        'error-container': '#ffdad6',
        surface: '#faf9f7',
        'on-secondary-fixed': '#1b1c1c',
        'on-primary': '#ffffff',
        'inverse-surface': '#2f3130',
        'surface-dim': '#dadad8',
        'on-primary-fixed-variant': '#733333',
        'on-primary-fixed': '#3b080b',
        'tertiary-container': '#444545',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '80px',
        xs: '4px',
        sm: '12px',
        gutter: '24px',
        lg: '48px',
        base: '8px',
        md: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'body-lg': ['Poppins', 'sans-serif'],
        'display-lg-mobile': ['Poppins', 'sans-serif'],
        'headline-md': ['Poppins', 'sans-serif'],
        'headline-lg': ['Poppins', 'sans-serif'],
        caption: ['Poppins', 'sans-serif'],
        'label-md': ['Poppins', 'sans-serif'],
        'display-lg': ['Poppins', 'sans-serif'],
        'body-md': ['Poppins', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      maxWidth: {
        content: '1280px',
      },
    },
  },
  plugins: [],
};
